resources:
- name: calico-concourse-ci
  type: git
  source:
    uri: https://github.com/djosborne/calico-concourse-ci.git
- name: libcalico-go
  type: git
  source:
    uri: https://github.com/projectcalico/libcalico-go.git
- name: calicoctl
  type: git
  source:
    uri: https://github.com/projectcalico/calicoctl.git
# - name: calico-node-docker-image
#   type: docker-image
#   source:
#     repository: djosborne/node

jobs:
- name: libcalico-go
  plan:
  - get: calico-concourse-ci
    trigger: true
  - get: libcalico-go
    trigger: true
  - task: unit-test
    config:
      platform: linux
      inputs:
      - name: libcalico-go
      image_resource:
        type: docker-image
        source: {repository: calico/go-build}
      run:
        dir: ./libcalico-go
        path: ../calico-concourse-ci/bin/libcalico-go/run-uts

- name: calicoctl
  plan:
  - get: libcalico-go
    passed: [libcalico-go]
  - get: calicoctl
  - task: build
    config:
      platform: linux
      inputs:
      - name: libcalico-go
      image_resource:
        type: docker-image
        source: {repository: calico/go-build}
      run:
        dir: ./calicoctl
        path: ./run-uts

# - name: calico-node
#   plan:
#   - get: libcalico-go
#     passed: [libcalico-go]
#   - put: calico-node-docker-image
#     params: {build: calico-node-docker-image}
